name: MinerSeller
version: '${project.version}'
main: top.lordgamer.minerseller.MinerSellerPlugin
api-version: '1.19'
author: LordGamer TOP
description: GUI shop for ores and resources.
softdepend: [Vault]

commands:
  miner:
    description: Open seller menu
    usage: /miner [reload]
    aliases: [minebuyer, rudy]
    permission: minerseller.use

permissions:
  minerseller.use:
    description: Access to seller menu
    default: true
  minerseller.admin:
    description: Access to /miner reload
    default: op
